"""
Graph Retriever - retrieves relevant context nodes for rating a specific criterion.

Given a criterion and a transcript, finds the most relevant nodes from the
context graph to include in the rating prompt. This solves the "context too big"
problem by only feeding relevant chunks to the model.
"""

import re
from typing import List, Optional
from .graph import ContextGraph, Node


class GraphRetriever:
    """Retrieves relevant context from a ContextGraph."""

    def __init__(self, graph: ContextGraph):
        self.graph = graph

    def retrieve_for_criterion(self, criterion: str, max_nodes: int = 30) -> List[Node]:
        """
        Retrieve all relevant nodes for a specific rating criterion.

        Args:
            criterion: The criterion category (e.g., "script_compliance")
            max_nodes: Maximum nodes to return

        Returns:
            List of relevant nodes, sorted by relevance
        """
        # Get direct category matches
        direct = self.graph.find_nodes_by_category(criterion)

        # Get related nodes via edges
        related = []
        for node in direct:
            neighbors = self.graph.get_neighbors(node.node_id, relation="related_to")
            related.extend(neighbors)

        # Combine and deduplicate
        seen = set()
        result = []
        for node in direct + related:
            if node.node_id not in seen and node.active:
                seen.add(node.node_id)
                # Follow same_concept edges to get canonical version
                canonical = self.graph.get_canonical_node(node.node_id)
                if canonical.node_id not in seen:
                    seen.add(canonical.node_id)
                    result.append(canonical)
                elif canonical.node_id == node.node_id:
                    result.append(node)

        return result[:max_nodes]

    def retrieve_by_semantic_tags(
        self,
        transcript: str,
        criterion: str,
        max_nodes: int = 20,
    ) -> List[Node]:
        """
        Retrieve nodes by matching their LLM-curated semantic_tags against the transcript.

        This is the Zettelkasten-style retrieval path. Node tags were generated by the
        LLM at ingestion time — specific, synonym-aware, and far more reliable than
        extracting keywords from the transcript by word frequency.

        For each node, counts how many of its semantic_tags appear as substrings in the
        transcript. Nodes with more tag hits rank higher. All criterion nodes are
        returned (sorted by relevance) so no relevant policy is silently dropped.

        Falls back to retrieve_by_transcript_keywords for old-format graphs where
        nodes have no semantic_tags.
        """
        # Direct filter: active, correct category, not a hub node
        criterion_nodes = [
            n for n in self.graph.nodes.values()
            if n.category == criterion and n.active and not n.is_hub
        ]

        if not criterion_nodes:
            return []

        # If nodes have no semantic_tags (old-format graph), use legacy method
        if not any(n.semantic_tags for n in criterion_nodes):
            return self.retrieve_by_transcript_keywords(transcript, criterion, max_nodes)

        transcript_lower = transcript.lower()
        scored = []

        for node in criterion_nodes:
            # Follow supersedes chain to get the canonical (latest) version's tags
            canonical = self.graph.get_canonical_node(node.node_id)
            tags = canonical.semantic_tags if canonical.semantic_tags else node.semantic_tags

            # Count how many tags appear anywhere in the transcript (case-insensitive).
            # Three matching strategies (in order):
            #   1. Direct:     "autopay"       in transcript
            #   2. Normalized: "wireless-specialist" → "wireless specialist" in transcript
            #   3. Component:  "5gb-data" → "5gb" in transcript (for numeric/short compounds)
            def _tag_in(tag: str, text: str) -> bool:
                t = tag.lower()
                if t in text:
                    return True
                normalized = t.replace("-", " ")
                if normalized in text:
                    return True
                # Check individual hyphen-separated components (4+ chars to avoid noise)
                parts = [p for p in t.split("-") if len(p) >= 4]
                return any(p in text for p in parts)

            hits = sum(1 for tag in tags if _tag_in(tag, transcript_lower))
            scored.append((hits, node))

        # Sort by hit count descending; nodes with 0 hits still included (policy always relevant)
        scored.sort(key=lambda x: x[0], reverse=True)
        return [n for _, n in scored[:max_nodes]]

    def retrieve_by_transcript_keywords(
        self,
        transcript: str,
        criterion: str,
        max_nodes: int = 20
    ) -> List[Node]:
        """
        Legacy retrieval: score criterion nodes by transcript word frequency overlap.
        Kept for backward compatibility with old-format graphs (no semantic_tags).
        Prefer retrieve_by_semantic_tags for new graphs.
        """
        # Extract keywords from transcript
        words = re.findall(r'\b[a-zA-Z]{3,}\b', transcript.lower())
        # Count frequency
        freq = {}
        for w in words:
            freq[w] = freq.get(w, 0) + 1
        # Top keywords by frequency (skip very common words)
        stop = {"the", "and", "for", "that", "this", "with", "you", "your",
                "have", "has", "was", "are", "been", "can", "will", "just",
                "not", "but", "what", "all", "any", "how", "they", "them"}
        top_keywords = sorted(
            [(w, c) for w, c in freq.items() if w not in stop],
            key=lambda x: x[1], reverse=True
        )[:30]
        kw_list = [w for w, _ in top_keywords]

        # Get criterion nodes (excluding hubs)
        criterion_nodes = [
            n for n in self.graph.nodes.values()
            if n.category == criterion and n.active and not n.is_hub
        ]

        # Score by transcript relevance
        scored = []
        for node in criterion_nodes:
            content_lower = node.content.lower()
            node_kw = set(k.lower() for k in node.keywords)
            content_score = sum(1 for k in kw_list if k in content_lower)
            kw_score = len(node_kw & set(kw_list)) * 2
            total = content_score + kw_score
            scored.append((total, node))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [node for _, node in scored[:max_nodes]]

    def format_context_for_prompt(
        self,
        nodes: List[Node],
        include_metadata: bool = False
    ) -> str:
        """
        Format retrieved nodes into a text block suitable for inclusion in a prompt.

        Groups nodes by topic for clarity.
        """
        if not nodes:
            return "No specific company context available for this criterion."

        # Group by topic
        by_topic = {}
        for node in nodes:
            by_topic.setdefault(node.topic, []).append(node)

        lines = []
        for topic, topic_nodes in sorted(by_topic.items()):
            topic_title = topic.replace("_", " ").title()
            lines.append(f"### {topic_title}")
            for node in topic_nodes:
                type_label = node.node_type.upper()
                lines.append(f"[{type_label}] {node.content}")
                # Check for equivalent versions
                equivalents = self.graph.find_equivalent_nodes(node.node_id)
                if equivalents:
                    lines.append(f"  (Also expressed as: {equivalents[0].content})")
            lines.append("")

        return "\n".join(lines)
